Repository michelin/ns4kafka, pull requests merged in 2023-01, with the labels that each got.

#228 Fixed connector change state URL in Kafkactl
  .github/workflows/on_pull_request.yml
  .github/workflows/on_push_master.yml
  .github/workflows/on_push_tag.yml
  api/src/test/java/com/michelin/ns4kafka/security/ResourceBasedSecurityRuleTest.java
  cli/src/main/java/com/michelin/ns4kafka/cli/client/NamespacedResourceClient.java
Labels: bug

#225 Allowed use of wildcard as ACLs grantedTo specification to manage public topics
  api/src/main/java/com/michelin/ns4kafka/controllers/AccessControlListController.java
  api/src/main/java/com/michelin/ns4kafka/controllers/AkhqClaimProviderController.java
  api/src/main/java/com/michelin/ns4kafka/services/AccessControlEntryService.java
  api/src/main/java/com/michelin/ns4kafka/services/executors/AccessControlEntryAsyncExecutor.java
  api/src/test/java/com/michelin/ns4kafka/controllers/AccessControlListControllerTest.java
  api/src/test/java/com/michelin/ns4kafka/controllers/AkhqClaimProviderControllerTest.java
  api/src/test/java/com/michelin/ns4kafka/services/AccessControlEntryServiceTest.java
Labels: component: API, feature

#232 Updated versioning plugin
  build.gradle
  semantic-build-versioning.gradle
  settings.gradle
Labels: bug

#233 Removed unused profile
  .github/workflows/on_push_tag.yml
Labels: refactor

#234 Removed unused environment
  .github/workflows/on_pull_request.yml
  .github/workflows/on_push_master.yml
  .github/workflows/on_push_tag.yml
Labels: refactor

#235 Upgraded to Micronaut 3.8.1
  .github/workflows/on_push_master.yml
  .github/workflows/on_push_tag.yml
  build.gradle
  gradle.properties
Labels: refactor

#236 Changed "Other" release note section icon to :speech_balloon:
  changelog-builder.json
Labels: documentation

#237 Changed javax PostConstruct to jakarta
  src/main/java/com/michelin/ns4kafka/repositories/kafka/KafkaStore.java
Labels: refactor

#238 Added dependency updates section in release note
  changelog-builder.json
Labels: feature

#239 Added dependabot
  .github/dependabot.yml
Labels: feature

#241 Fixed null in event log on namespace creation
  src/main/java/com/michelin/ns4kafka/controllers/ConnectorController.java
  src/main/java/com/michelin/ns4kafka/controllers/NamespaceController.java
  src/test/java/com/michelin/ns4kafka/controllers/NamespaceControllerTest.java
Labels: enhancement

#242 Updated deprecated sonarqube task
  .github/workflows/on_pull_request.yml
  .github/workflows/on_push_master.yml
Labels: enhancement

#244 Added github actions to dependabot
  .github/dependabot.yml
Labels: enhancement

#246 Decreased the number of calls to GitLab groups API during authentication
  src/main/java/com/michelin/ns4kafka/security/gitlab/GitlabApiClient.java
  src/main/java/com/michelin/ns4kafka/security/gitlab/GitlabAuthenticationService.java
Labels: enhancement

#249 Fixed error on empty topic validation constraints
  src/main/java/com/michelin/ns4kafka/controllers/topic/TopicController.java
  src/main/java/com/michelin/ns4kafka/services/ConnectorService.java
  src/main/java/com/michelin/ns4kafka/validation/TopicValidator.java
  src/test/java/com/michelin/ns4kafka/controllers/TopicControllerTest.java
  src/test/java/com/michelin/ns4kafka/models/TopicValidatorTest.java
Labels: bug

#245 Added AES256 vault capability for Kafka Connect clusters
  build.gradle
  src/main/java/com/michelin/ns4kafka/controllers/ConnectClusterController.java
  src/main/java/com/michelin/ns4kafka/models/ConnectCluster.java
  src/main/java/com/michelin/ns4kafka/services/ConnectClusterService.java
  src/main/java/com/michelin/ns4kafka/utils/EncryptionUtils.java
  src/test/java/com/michelin/ns4kafka/controllers/ConnectClusterControllerTest.java
  src/test/java/com/michelin/ns4kafka/services/ConnectClusterServiceTest.java
  src/test/java/com/michelin/ns4kafka/utils/EncryptionUtilsTest.java
Labels: feature

#250 Improved unit tests coverage on connector validator
  src/main/java/com/michelin/ns4kafka/services/ConsumerGroupService.java
  src/main/java/com/michelin/ns4kafka/utils/ValidationErrorUtils.java
  src/main/java/com/michelin/ns4kafka/validation/ConnectValidator.java
  src/test/java/com/michelin/ns4kafka/models/ConnectValidatorTest.java
Labels: enhancement
