Repository michelin/ns4kafka, pull requests merged in 2023-02, with the labels that each got.

#252 Blurred Connect cluster AES256 keys and secrets for non-owners
  src/main/java/com/michelin/ns4kafka/controllers/ConnectClusterController.java
  src/main/java/com/michelin/ns4kafka/models/connect/cluster/ConnectCluster.java
  src/main/java/com/michelin/ns4kafka/models/connect/cluster/VaultResponse.java
  src/main/java/com/michelin/ns4kafka/repositories/ConnectClusterRepository.java
  src/main/java/com/michelin/ns4kafka/repositories/kafka/KafkaConnectClusterRepository.java
  src/main/java/com/michelin/ns4kafka/services/ConnectClusterService.java
  src/main/java/com/michelin/ns4kafka/services/connect/ConnectorClientProxy.java
  src/test/java/com/michelin/ns4kafka/controllers/ConnectClusterControllerTest.java
  src/test/java/com/michelin/ns4kafka/services/ConnectClusterServiceTest.java
  src/test/java/com/michelin/ns4kafka/services/ConnectorClientProxyTest.java
  src/test/java/com/michelin/ns4kafka/services/ConnectorServiceTest.java
Labels: enhancement

#254 Fixed namespace status always displays created
  src/main/java/com/michelin/ns4kafka/repositories/kafka/KafkaNamespaceRepository.java
  src/main/java/com/michelin/ns4kafka/security/gitlab/GitlabAuthenticationProvider.java
  src/main/java/com/michelin/ns4kafka/validation/ConnectValidator.java
  src/main/java/com/michelin/ns4kafka/validation/ResourceValidator.java
  src/main/java/com/michelin/ns4kafka/validation/TopicValidator.java
Labels: bug

#255 Displayed schema status created/updated in dry mode
  src/main/java/com/michelin/ns4kafka/controllers/SchemaController.java
  src/main/java/com/michelin/ns4kafka/models/schema/Schema.java
  src/test/java/com/michelin/ns4kafka/controllers/SchemaControllerTest.java
Labels: enhancement

#256 Added Transactional ID ACL
  src/main/java/com/michelin/ns4kafka/controllers/acl/AccessControlListController.java
  src/main/java/com/michelin/ns4kafka/models/AccessControlEntry.java
  src/main/java/com/michelin/ns4kafka/services/executors/AccessControlEntryAsyncExecutor.java
  src/test/java/com/michelin/ns4kafka/controllers/AccessControlListControllerTest.java
  src/test/java/com/michelin/ns4kafka/integration/AccessControlListTest.java
Labels: feature
