Repository michelin/ns4kafka, pull requests merged in 2023-10, with the labels that each got.

#325 Add GitHub Actions for tagging
  .github/workflows/tag.yml
Labels: enhancement

#326 Restore Micronaut management
  build.gradle
Labels: bug

#328 Add key/value suffix for schema filtering on LITERAL ACL on v3 claim
  src/main/java/com/michelin/ns4kafka/controllers/AkhqClaimProviderController.java
  src/test/java/com/michelin/ns4kafka/controllers/AkhqClaimProviderControllerV3Test.java
Labels: bug

#321 Manage Confluent Cloud tags
  README.md
  src/main/java/com/michelin/ns4kafka/controllers/topic/TopicController.java
  src/main/java/com/michelin/ns4kafka/models/ObjectMeta.java
  src/main/java/com/michelin/ns4kafka/models/Topic.java
  src/main/java/com/michelin/ns4kafka/services/TopicService.java
  src/main/java/com/michelin/ns4kafka/services/clients/schema/SchemaRegistryClient.java
  src/main/java/com/michelin/ns4kafka/services/clients/schema/entities/TagInfo.java
  src/main/java/com/michelin/ns4kafka/services/clients/schema/entities/TagTopicInfo.java
  src/main/java/com/michelin/ns4kafka/services/executors/AccessControlEntryAsyncExecutor.java
  src/main/java/com/michelin/ns4kafka/services/executors/ConnectorAsyncExecutor.java
  src/main/java/com/michelin/ns4kafka/services/executors/ConsumerGroupAsyncExecutor.java
  src/main/java/com/michelin/ns4kafka/services/executors/KafkaAsyncExecutorScheduler.java
  src/main/java/com/michelin/ns4kafka/services/executors/TopicAsyncExecutor.java
  src/main/java/com/michelin/ns4kafka/services/executors/UserAsyncExecutor.java
  src/test/java/com/michelin/ns4kafka/controllers/TopicControllerTest.java
  src/test/java/com/michelin/ns4kafka/integration/UserTest.java
  src/test/java/com/michelin/ns4kafka/services/TopicServiceTest.java
  src/test/java/com/michelin/ns4kafka/services/executors/TopicAsyncExecutorTest.java
Labels: feature

#331 Fix tag job
  .github/workflows/tag.yml
Labels: bug

#334 Replace Account ID by Resource ID on Confluent Cloud
  src/main/java/com/michelin/ns4kafka/services/executors/AccessControlEntryAsyncExecutor.java
Labels: feature
