Repository michelin/ns4kafka, pull requests merged in 2024-03, with the labels that each got.

#381 Unauthorize min.cleanable.dirty.ratio on Confluent Cloud
  src/main/java/com/michelin/ns4kafka/controllers/ExceptionHandlerController.java
  src/main/java/com/michelin/ns4kafka/properties/ManagedClusterProperties.java
  src/main/java/com/michelin/ns4kafka/services/NamespaceService.java
  src/main/java/com/michelin/ns4kafka/services/TopicService.java
  src/main/java/com/michelin/ns4kafka/services/executors/TopicAsyncExecutor.java
  src/main/java/com/michelin/ns4kafka/services/executors/UserAsyncExecutor.java
  src/main/java/com/michelin/ns4kafka/utils/FormatErrorUtils.java
  src/test/java/com/michelin/ns4kafka/integration/ExceptionHandlerTest.java
  src/test/java/com/michelin/ns4kafka/integration/NamespaceTest.java
  src/test/java/com/michelin/ns4kafka/integration/SchemaTest.java
  src/test/java/com/michelin/ns4kafka/integration/TopicTest.java
  src/test/java/com/michelin/ns4kafka/services/NamespaceServiceTest.java
  src/test/java/com/michelin/ns4kafka/services/TopicServiceTest.java
  src/test/java/com/michelin/ns4kafka/services/executors/TopicAsyncExecutorTest.java
Labels: bug

#383 Add topic description on Confluent Cloud
  src/main/java/com/michelin/ns4kafka/models/Topic.java
  src/main/java/com/michelin/ns4kafka/services/TopicService.java
  src/main/java/com/michelin/ns4kafka/services/clients/schema/SchemaRegistryClient.java
  src/main/java/com/michelin/ns4kafka/services/clients/schema/entities/TagEntity.java
  src/main/java/com/michelin/ns4kafka/services/clients/schema/entities/TopicDescriptionUpdateAttributes.java
  src/main/java/com/michelin/ns4kafka/services/clients/schema/entities/TopicDescriptionUpdateBody.java
  src/main/java/com/michelin/ns4kafka/services/clients/schema/entities/TopicDescriptionUpdateEntity.java
  src/main/java/com/michelin/ns4kafka/services/clients/schema/entities/TopicDescriptionUpdateResponse.java
  src/main/java/com/michelin/ns4kafka/services/clients/schema/entities/TopicEntity.java
  src/main/java/com/michelin/ns4kafka/services/clients/schema/entities/TopicEntityAttributes.java
  src/main/java/com/michelin/ns4kafka/services/clients/schema/entities/TopicListResponse.java
  src/main/java/com/michelin/ns4kafka/services/executors/TopicAsyncExecutor.java
  src/main/java/com/michelin/ns4kafka/utils/FormatErrorUtils.java
  src/test/java/com/michelin/ns4kafka/services/TopicServiceTest.java
  src/test/java/com/michelin/ns4kafka/services/executors/TopicAsyncExecutorTest.java
Labels: feature

#384 Optimize JWT content with role bindings
  .docker/resources/user/connect-cluster.yml
  README.md
  src/main/java/com/michelin/ns4kafka/controllers/ApiResourcesController.java
  src/main/java/com/michelin/ns4kafka/controllers/acl/AclController.java
  src/main/java/com/michelin/ns4kafka/models/RoleBinding.java
  src/main/java/com/michelin/ns4kafka/properties/SecurityProperties.java
  src/main/java/com/michelin/ns4kafka/security/ResourceBasedSecurityRule.java
  src/main/java/com/michelin/ns4kafka/security/auth/AuthenticationService.java
  src/main/java/com/michelin/ns4kafka/security/auth/JwtField.java
  src/main/java/com/michelin/ns4kafka/security/auth/JwtRoleBinding.java
  src/main/java/com/michelin/ns4kafka/security/auth/gitlab/GitlabApiClient.java
  src/main/java/com/michelin/ns4kafka/security/auth/gitlab/GitlabAuthenticationProvider.java
  src/main/java/com/michelin/ns4kafka/security/auth/gitlab/GitlabAuthenticationService.java
  src/main/java/com/michelin/ns4kafka/security/auth/gitlab/package-info.java
  src/main/java/com/michelin/ns4kafka/security/auth/ldap/LdapAuthenticationMapper.java
  src/main/java/com/michelin/ns4kafka/security/auth/local/LocalUser.java
  src/main/java/com/michelin/ns4kafka/security/auth/local/LocalUserAuthenticationProvider.java
  src/test/java/com/michelin/ns4kafka/integration/ExceptionHandlerTest.java
  src/test/java/com/michelin/ns4kafka/integration/NamespaceTest.java
  src/test/java/com/michelin/ns4kafka/security/ResourceBasedSecurityRuleTest.java
  src/test/java/com/michelin/ns4kafka/security/auth/AuthenticationServiceTest.java
  src/test/java/com/michelin/ns4kafka/security/auth/gitlab/GitlabAuthenticationProviderTest.java
  src/test/java/com/michelin/ns4kafka/security/auth/gitlab/GitlabAuthenticationServiceTest.java
  src/test/java/com/michelin/ns4kafka/security/auth/ldap/LdapAuthenticationMapperTest.java
  src/test/java/com/michelin/ns4kafka/security/auth/local/LocalUserAuthenticationProviderTest.java
Labels: enhancement
