Repository michelin/ns4kafka, pull requests merged in 2024-07, with the labels that each got.

#405 Add documentation about Stream Catalog configuration
  README.md
Labels: documentation

#409 Fix misspelling in Managed Cluster section
  README.md
Labels: documentation

#417 Fix ACL being deleted from owner Kafka user even when granted to another namespace
  CONTRIBUTING.md
  src/main/java/com/michelin/ns4kafka/controller/AkhqClaimProviderController.java
  src/main/java/com/michelin/ns4kafka/controller/acl/AclController.java
  src/main/java/com/michelin/ns4kafka/controller/acl/AclNonNamespacedController.java
  src/main/java/com/michelin/ns4kafka/repository/kafka/KafkaNamespaceRepository.java
  src/main/java/com/michelin/ns4kafka/service/AclService.java
  src/main/java/com/michelin/ns4kafka/service/ConnectClusterService.java
  src/main/java/com/michelin/ns4kafka/service/ConnectorService.java
  src/main/java/com/michelin/ns4kafka/service/ConsumerGroupService.java
  src/main/java/com/michelin/ns4kafka/service/NamespaceService.java
  src/main/java/com/michelin/ns4kafka/service/SchemaService.java
  src/main/java/com/michelin/ns4kafka/service/StreamService.java
  src/main/java/com/michelin/ns4kafka/service/TopicService.java
  src/main/java/com/michelin/ns4kafka/service/executor/AccessControlEntryAsyncExecutor.java
  src/main/java/com/michelin/ns4kafka/util/FormatErrorUtils.java
  src/test/java/com/michelin/ns4kafka/controller/AclControllerTest.java
  src/test/java/com/michelin/ns4kafka/controller/AclNonNamespacedControllerTest.java
  src/test/java/com/michelin/ns4kafka/controller/AkhqClaimProviderControllerTest.java
  src/test/java/com/michelin/ns4kafka/controller/AkhqClaimProviderControllerV3Test.java
  src/test/java/com/michelin/ns4kafka/integration/AccessControlListTest.java
  src/test/java/com/michelin/ns4kafka/integration/AclIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/integration/ApiResourcesIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/integration/ConnectIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/integration/ExceptionHandlerIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/integration/LoginIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/integration/NamespaceIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/integration/SchemaIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/integration/StreamIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/integration/TopicIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/integration/UserIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/service/AclServiceTest.java
  src/test/java/com/michelin/ns4kafka/service/ConnectClusterServiceTest.java
  src/test/java/com/michelin/ns4kafka/service/ConnectorServiceTest.java
  src/test/java/com/michelin/ns4kafka/service/NamespaceServiceTest.java
  src/test/java/com/michelin/ns4kafka/service/SchemaServiceTest.java
  src/test/java/com/michelin/ns4kafka/service/StreamServiceTest.java
  src/test/java/com/michelin/ns4kafka/service/TopicServiceTest.java
Labels: bug

#422 Fix connect cluster apply when there is no connect cluster in Ns4Kafka configuration
  src/main/java/com/michelin/ns4kafka/controller/connect/ConnectClusterController.java
  src/main/java/com/michelin/ns4kafka/service/ConnectClusterService.java
  src/main/java/com/michelin/ns4kafka/service/ConnectorService.java
  src/main/java/com/michelin/ns4kafka/service/NamespaceService.java
  src/test/java/com/michelin/ns4kafka/controller/ConnectClusterControllerTest.java
  src/test/java/com/michelin/ns4kafka/service/ConnectClusterServiceTest.java
  src/test/java/com/michelin/ns4kafka/service/ConnectorServiceTest.java
  src/test/java/com/michelin/ns4kafka/service/NamespaceServiceTest.java
Labels: bug

#411 Handle wildcard parameter in Streams list API
  src/main/java/com/michelin/ns4kafka/controller/StreamController.java
  src/main/java/com/michelin/ns4kafka/service/StreamService.java
  src/main/java/com/michelin/ns4kafka/util/RegexUtils.java
  src/test/java/com/michelin/ns4kafka/controller/StreamControllerTest.java
  src/test/java/com/michelin/ns4kafka/service/StreamServiceTest.java
  src/test/java/com/michelin/ns4kafka/util/RegexUtilsTest.java
Labels: feature

#410 Handle wildcard parameter in Topic list API
  src/main/java/com/michelin/ns4kafka/controller/topic/TopicController.java
  src/main/java/com/michelin/ns4kafka/service/AclService.java
  src/main/java/com/michelin/ns4kafka/service/TopicService.java
  src/test/java/com/michelin/ns4kafka/controller/TopicControllerTest.java
  src/test/java/com/michelin/ns4kafka/service/AclServiceTest.java
  src/test/java/com/michelin/ns4kafka/service/TopicServiceTest.java
Labels: feature

#412 Handle wildcard parameter in Schema list API
  src/main/java/com/michelin/ns4kafka/controller/SchemaController.java
  src/main/java/com/michelin/ns4kafka/service/AclService.java
  src/main/java/com/michelin/ns4kafka/service/SchemaService.java
  src/test/java/com/michelin/ns4kafka/controller/SchemaControllerTest.java
  src/test/java/com/michelin/ns4kafka/service/AclServiceTest.java
  src/test/java/com/michelin/ns4kafka/service/SchemaServiceTest.java
Labels: feature

#413 Handle wildcard parameter in RoleBinding list API
  src/main/java/com/michelin/ns4kafka/controller/RoleBindingController.java
  src/main/java/com/michelin/ns4kafka/security/auth/AuthenticationService.java
  src/main/java/com/michelin/ns4kafka/service/NamespaceService.java
  src/main/java/com/michelin/ns4kafka/service/RoleBindingService.java
  src/test/java/com/michelin/ns4kafka/controller/RoleBindingControllerTest.java
  src/test/java/com/michelin/ns4kafka/security/auth/AuthenticationServiceTest.java
  src/test/java/com/michelin/ns4kafka/service/NamespaceServiceTest.java
  src/test/java/com/michelin/ns4kafka/service/RoleBindingServiceTest.java
Labels: feature

#418 Handle wildcard parameter in Namespace list API
  src/main/java/com/michelin/ns4kafka/controller/AkhqClaimProviderController.java
  src/main/java/com/michelin/ns4kafka/controller/NamespaceController.java
  src/main/java/com/michelin/ns4kafka/controller/quota/ResourceQuotaNonNamespacedController.java
  src/main/java/com/michelin/ns4kafka/service/NamespaceService.java
  src/main/java/com/michelin/ns4kafka/util/RegexUtils.java
  src/test/java/com/michelin/ns4kafka/controller/AkhqClaimProviderControllerTest.java
  src/test/java/com/michelin/ns4kafka/controller/AkhqClaimProviderControllerV3Test.java
  src/test/java/com/michelin/ns4kafka/controller/NamespaceControllerTest.java
  src/test/java/com/michelin/ns4kafka/controller/ResourceQuotaNonNamespacedControllerTest.java
  src/test/java/com/michelin/ns4kafka/controller/TopicNonNamespacedControllerTest.java
  src/test/java/com/michelin/ns4kafka/integration/ApiResourcesIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/integration/ExceptionHandlerIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/integration/LoginIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/integration/NamespaceIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/integration/SchemaIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/integration/StreamIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/integration/TopicIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/integration/UserIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/service/NamespaceServiceTest.java
Labels: feature
