Repository michelin/ns4kafka, pull requests merged in 2024-08, with the labels that each got.

#426 Fix task state check in connector integration tests
  src/test/java/com/michelin/ns4kafka/integration/ConnectIntegrationTest.java
Labels: bug

#427 Handle wildcard parameter in ResourceQuota list API
  src/main/java/com/michelin/ns4kafka/controller/quota/ResourceQuotaController.java
  src/main/java/com/michelin/ns4kafka/repository/kafka/KafkaResourceQuotaRepository.java
  src/main/java/com/michelin/ns4kafka/service/NamespaceService.java
  src/main/java/com/michelin/ns4kafka/service/ResourceQuotaService.java
  src/test/java/com/michelin/ns4kafka/controller/ResourceQuotaControllerTest.java
  src/test/java/com/michelin/ns4kafka/service/NamespaceServiceTest.java
  src/test/java/com/michelin/ns4kafka/service/ResourceQuotaServiceTest.java
Labels: feature

#425 Handle wildcard parameter in ACL list API
  src/main/java/com/michelin/ns4kafka/controller/acl/AclController.java
  src/main/java/com/michelin/ns4kafka/repository/kafka/KafkaStore.java
  src/main/java/com/michelin/ns4kafka/service/AclService.java
  src/main/java/com/michelin/ns4kafka/service/ConnectClusterService.java
  src/main/java/com/michelin/ns4kafka/service/ConnectorService.java
  src/main/java/com/michelin/ns4kafka/service/NamespaceService.java
  src/main/java/com/michelin/ns4kafka/service/ResourceQuotaService.java
  src/main/java/com/michelin/ns4kafka/service/RoleBindingService.java
  src/main/java/com/michelin/ns4kafka/service/SchemaService.java
  src/main/java/com/michelin/ns4kafka/service/StreamService.java
  src/main/java/com/michelin/ns4kafka/service/TopicService.java
  src/main/java/com/michelin/ns4kafka/util/RegexUtils.java
  src/test/java/com/michelin/ns4kafka/controller/AclControllerTest.java
  src/test/java/com/michelin/ns4kafka/controller/AkhqClaimProviderControllerTest.java
  src/test/java/com/michelin/ns4kafka/controller/AkhqClaimProviderControllerV3Test.java
  src/test/java/com/michelin/ns4kafka/controller/ConnectClusterControllerTest.java
  src/test/java/com/michelin/ns4kafka/controller/ConnectClusterNonNamespacedControllerTest.java
  src/test/java/com/michelin/ns4kafka/controller/ConsumerGroupControllerTest.java
  src/test/java/com/michelin/ns4kafka/controller/ResourceQuotaNonNamespacedControllerTest.java
  src/test/java/com/michelin/ns4kafka/integration/AclIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/integration/ApiResourcesIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/integration/ConnectIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/integration/ExceptionHandlerIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/integration/NamespaceIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/integration/SchemaIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/integration/StreamIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/integration/TopicIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/integration/UserIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/model/AccessControlEntryTest.java
  src/test/java/com/michelin/ns4kafka/model/ConnectValidatorTest.java
  src/test/java/com/michelin/ns4kafka/model/ConnectorTest.java
  src/test/java/com/michelin/ns4kafka/model/MetadataTest.java
  src/test/java/com/michelin/ns4kafka/model/NamespaceTest.java
  src/test/java/com/michelin/ns4kafka/model/ResourceValidatorTest.java
  src/test/java/com/michelin/ns4kafka/model/RoleBindingTest.java
  src/test/java/com/michelin/ns4kafka/model/SchemaTest.java
  src/test/java/com/michelin/ns4kafka/model/StreamTest.java
  src/test/java/com/michelin/ns4kafka/model/TopicTest.java
  src/test/java/com/michelin/ns4kafka/model/TopicValidatorTest.java
  src/test/java/com/michelin/ns4kafka/security/auth/AuthenticationInfoTest.java
  src/test/java/com/michelin/ns4kafka/security/auth/AuthenticationServiceTest.java
  src/test/java/com/michelin/ns4kafka/security/auth/gitlab/GitlabAuthenticationProviderTest.java
  src/test/java/com/michelin/ns4kafka/security/auth/ldap/LdapAuthenticationMapperTest.java
  src/test/java/com/michelin/ns4kafka/security/auth/local/LocalUserAuthenticationProviderTest.java
  src/test/java/com/michelin/ns4kafka/service/AclServiceTest.java
  src/test/java/com/michelin/ns4kafka/service/ConnectClusterServiceTest.java
  src/test/java/com/michelin/ns4kafka/service/ConnectorServiceTest.java
  src/test/java/com/michelin/ns4kafka/service/ConsumerGroupServiceTest.java
  src/test/java/com/michelin/ns4kafka/service/SchemaServiceTest.java
  src/test/java/com/michelin/ns4kafka/service/TopicServiceTest.java
  src/test/java/com/michelin/ns4kafka/util/BytesUtilsTest.java
  src/test/java/com/michelin/ns4kafka/util/EncryptionUtilsTest.java
  src/test/java/com/michelin/ns4kafka/util/RegexUtilsTest.java
Labels: feature

#434 Migrate integration tests to KRaft broker
  .docker/config/broker/kafka_server_jaas.conf
  build.gradle
  src/main/java/com/michelin/ns4kafka/repository/kafka/KafkaStore.java
  src/main/java/com/michelin/ns4kafka/service/executor/TopicAsyncExecutor.java
  src/test/java/com/michelin/ns4kafka/integration/AbstractIntegrationConnectTest.java
  src/test/java/com/michelin/ns4kafka/integration/AbstractIntegrationSchemaRegistryTest.java
  src/test/java/com/michelin/ns4kafka/integration/AbstractIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/integration/AclIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/integration/ApiResourcesIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/integration/ConnectorIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/integration/ExceptionHandlerIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/integration/LoginIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/integration/NamespaceIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/integration/SchemaIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/integration/StreamIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/integration/TopicIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/integration/UserIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/integration/container/KafkaConnectIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/integration/container/KafkaIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/integration/container/SchemaRegistryIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/testcontainers/KafkaConnectContainer.java
  src/test/java/com/michelin/ns4kafka/testcontainers/SchemaRegistryContainer.java
  src/test/resources/application-test.yml
Labels: enhancement

#428 Delete a specific version of a schema
  src/main/java/com/michelin/ns4kafka/controller/ConnectorController.java
  src/main/java/com/michelin/ns4kafka/controller/ConsumerGroupController.java
  src/main/java/com/michelin/ns4kafka/controller/NamespaceController.java
  src/main/java/com/michelin/ns4kafka/controller/RoleBindingController.java
  src/main/java/com/michelin/ns4kafka/controller/SchemaController.java
  src/main/java/com/michelin/ns4kafka/controller/StreamController.java
  src/main/java/com/michelin/ns4kafka/controller/UserController.java
  src/main/java/com/michelin/ns4kafka/controller/acl/AclController.java
  src/main/java/com/michelin/ns4kafka/controller/connect/ConnectClusterController.java
  src/main/java/com/michelin/ns4kafka/controller/generic/ResourceController.java
  src/main/java/com/michelin/ns4kafka/controller/quota/ResourceQuotaController.java
  src/main/java/com/michelin/ns4kafka/controller/topic/TopicController.java
  src/main/java/com/michelin/ns4kafka/log/ConsoleLogListener.java
  src/main/java/com/michelin/ns4kafka/model/AuditLog.java
  src/main/java/com/michelin/ns4kafka/service/SchemaService.java
  src/main/java/com/michelin/ns4kafka/service/client/schema/SchemaRegistryClient.java
  src/main/java/com/michelin/ns4kafka/validation/ResourceValidator.java
  src/test/java/com/michelin/ns4kafka/controller/SchemaControllerTest.java
  src/test/java/com/michelin/ns4kafka/integration/SchemaIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/service/SchemaServiceTest.java
Labels: feature
