Repository michelin/ns4kafka, pull requests merged in 2025-06, with the labels that each got.

#569 Delete changelog and repartition topics when deleting Kafka Streams resources
  src/main/java/com/michelin/ns4kafka/controller/StreamController.java
  src/main/java/com/michelin/ns4kafka/service/StreamService.java
  src/main/java/com/michelin/ns4kafka/service/TopicService.java
  src/test/java/com/michelin/ns4kafka/controller/StreamControllerTest.java
  src/test/java/com/michelin/ns4kafka/service/StreamServiceTest.java
  src/test/java/com/michelin/ns4kafka/service/TopicServiceTest.java
Labels: enhancement

#578 Fix internal stream topics overlap deletion
  src/main/java/com/michelin/ns4kafka/service/StreamService.java
  src/test/java/com/michelin/ns4kafka/service/StreamServiceTest.java
Labels: bug

#586 Fix bump Schema Registry client to v8.0.0
  build.gradle
  src/main/resources/application.yml
Labels: dependencies
