Repository michelin/ns4kafka, pull requests merged in 2025-01, with the labels that each got.

#498 Make all AdminClient timeouts configurable
  README.md
  src/main/java/com/michelin/ns4kafka/property/ManagedClusterProperties.java
  src/main/java/com/michelin/ns4kafka/service/executor/AccessControlEntryAsyncExecutor.java
  src/main/java/com/michelin/ns4kafka/service/executor/ConsumerGroupAsyncExecutor.java
  src/main/java/com/michelin/ns4kafka/service/executor/TopicAsyncExecutor.java
  src/main/java/com/michelin/ns4kafka/service/executor/UserAsyncExecutor.java
  src/test/java/com/michelin/ns4kafka/integration/ConfigIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/service/executor/TopicAsyncExecutorTest.java
  src/test/resources/application-test.yml
Labels: enhancement

#500 Improve JWT format with namespaces grouping
  .docker/resources/admin/another-namespace2.yml
  README.md
  src/main/java/com/michelin/ns4kafka/security/ResourceBasedSecurityRule.java
  src/main/java/com/michelin/ns4kafka/security/auth/AuthenticationRoleBinding.java
  src/main/java/com/michelin/ns4kafka/security/auth/AuthenticationService.java
  src/test/java/com/michelin/ns4kafka/security/ResourceBasedSecurityRuleTest.java
  src/test/java/com/michelin/ns4kafka/security/auth/AuthenticationInfoTest.java
  src/test/java/com/michelin/ns4kafka/security/auth/AuthenticationServiceTest.java
  src/test/java/com/michelin/ns4kafka/security/auth/gitlab/GitlabAuthenticationProviderTest.java
  src/test/java/com/michelin/ns4kafka/security/auth/ldap/LdapAuthenticationMapperTest.java
  src/test/java/com/michelin/ns4kafka/security/auth/local/LocalUserAuthenticationProviderTest.java
Labels: enhancement

#503 Add logo
  .readme/logo.svg
  README.md
Labels: documentation

#497 Add protected namespaces possibility
  src/main/java/com/michelin/ns4kafka/controller/acl/AclController.java
  src/main/java/com/michelin/ns4kafka/model/Namespace.java
  src/main/java/com/michelin/ns4kafka/service/AclService.java
  src/main/java/com/michelin/ns4kafka/util/FormatErrorUtils.java
  src/test/java/com/michelin/ns4kafka/controller/AclControllerTest.java
  src/test/java/com/michelin/ns4kafka/integration/AclIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/integration/StreamIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/service/AclServiceTest.java
Labels: feature

#506 Add new API resources names
  src/main/java/com/michelin/ns4kafka/controller/ApiResourcesController.java
Labels: enhancement

#505 Make filtering parameters dynamic for LIST namespace API
  src/main/java/com/michelin/ns4kafka/controller/NamespaceController.java
  src/main/java/com/michelin/ns4kafka/service/NamespaceService.java
  src/test/java/com/michelin/ns4kafka/controller/NamespaceControllerTest.java
Labels: refactor
