Repository michelin/ns4kafka, pull requests merged in 2025-02, with the labels that each got.

#508 Update Ns4Kafka version in Docker-Compose
  .docker/config/akhq/application.yml
  .docker/config/kafkactl/config.yml
  .docker/config/ns4kafka/application.yml
  .docker/docker-compose-akhq.yml
  .docker/docker-compose.yml
  .docker/resources/admin/namespace.yml
Labels: dependencies

#509 Replace deprecated use of URL
  src/main/java/com/michelin/ns4kafka/controller/ConnectorController.java
  src/main/java/com/michelin/ns4kafka/controller/ConsumerGroupController.java
  src/main/java/com/michelin/ns4kafka/controller/ExceptionHandlerController.java
  src/main/java/com/michelin/ns4kafka/controller/NamespaceController.java
  src/main/java/com/michelin/ns4kafka/controller/RoleBindingController.java
  src/main/java/com/michelin/ns4kafka/controller/SchemaController.java
  src/main/java/com/michelin/ns4kafka/controller/StreamController.java
  src/main/java/com/michelin/ns4kafka/controller/UserController.java
  src/main/java/com/michelin/ns4kafka/controller/acl/AclController.java
  src/main/java/com/michelin/ns4kafka/controller/connect/ConnectClusterController.java
  src/main/java/com/michelin/ns4kafka/controller/quota/ResourceQuotaController.java
  src/main/java/com/michelin/ns4kafka/controller/topic/TopicController.java
  src/main/java/com/michelin/ns4kafka/model/Status.java
  src/main/java/com/michelin/ns4kafka/model/connector/ChangeConnectorState.java
  src/main/java/com/michelin/ns4kafka/service/ConnectClusterService.java
  src/main/java/com/michelin/ns4kafka/service/client/connect/KafkaConnectClient.java
  src/main/java/com/michelin/ns4kafka/util/FormatErrorUtils.java
  src/main/java/com/michelin/ns4kafka/util/enumation/ApplyStatus.java
  src/main/java/com/michelin/ns4kafka/validation/TopicValidator.java
  src/test/java/com/michelin/ns4kafka/controller/ConnectorControllerTest.java
  src/test/java/com/michelin/ns4kafka/integration/ConnectorIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/service/ConnectClusterServiceTest.java
  src/test/java/com/michelin/ns4kafka/service/TopicServiceTest.java
Labels: refactor

#513 Fix ignored default Stream catalog page size
  src/main/java/com/michelin/ns4kafka/property/ConfluentCloudProperties.java
Labels: bug

#512 Fix status and connector action serialization for old clients
  src/main/java/com/michelin/ns4kafka/controller/ExceptionHandlerController.java
  src/main/java/com/michelin/ns4kafka/model/Status.java
  src/main/java/com/michelin/ns4kafka/model/connector/ChangeConnectorState.java
Labels: bug

#514 Update deprecated usage of encrypt and decrypt
  src/main/java/com/michelin/ns4kafka/util/EncryptionUtils.java
Labels: enhancement

#515 Prevent SonarQube running on fork
  .github/workflows/pull_request.yml
  .github/workflows/push_master.yml
Labels: ci/cd

#516 Fix inconsistent failure in Connector integration tests due to unassigned tasks
  .docker/docker-compose-akhq.yml
  .docker/docker-compose.yml
  src/main/java/com/michelin/ns4kafka/service/ConnectClusterService.java
  src/main/java/com/michelin/ns4kafka/service/executor/ConnectorAsyncExecutor.java
  src/test/java/com/michelin/ns4kafka/integration/ConnectClusterIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/integration/ConnectorIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/integration/container/KafkaConnectIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/integration/container/KafkaIntegrationTest.java
Labels: ci/cd

#518 Fix obsolete ACLs after namespace deletion
  src/main/java/com/michelin/ns4kafka/service/AclService.java
  src/main/java/com/michelin/ns4kafka/service/NamespaceService.java
  src/test/java/com/michelin/ns4kafka/service/AclServiceTest.java
  src/test/java/com/michelin/ns4kafka/service/NamespaceServiceTest.java
Labels: bug
