Repository michelin/ns4kafka, pull requests merged in 2025-08, with the labels that each got.

#610 Add the possibility to override the support groups delimiter
  src/main/java/com/michelin/ns4kafka/controller/AkhqClaimProviderController.java
  src/main/java/com/michelin/ns4kafka/property/Ns4KafkaProperties.java
  src/main/resources/application.yml
  src/test/java/com/michelin/ns4kafka/controller/AkhqClaimProviderControllerV3Test.java
Labels: feature

#613 Bump Micronaut HTTP Client to 4.9.10
  build.gradle
Labels: dependencies

#620 Add missing AKHQ configuration explanation
  README.md
Labels: documentation

#618 Add the possibility to import specific topics
  src/main/java/com/michelin/ns4kafka/controller/topic/TopicController.java
  src/main/java/com/michelin/ns4kafka/service/TopicService.java
  src/test/java/com/michelin/ns4kafka/controller/TopicControllerTest.java
  src/test/java/com/michelin/ns4kafka/service/TopicServiceTest.java
Labels: feature

#619 Fix topic update and delete-records when no cleanup policy
  src/main/java/com/michelin/ns4kafka/service/TopicService.java
  src/main/java/com/michelin/ns4kafka/util/FormatErrorUtils.java
  src/test/java/com/michelin/ns4kafka/service/TopicServiceTest.java
Labels: bug

#622 Fix cleanup policy update conditions for Confluent Cloud
  src/main/java/com/michelin/ns4kafka/service/TopicService.java
  src/main/java/com/michelin/ns4kafka/util/FormatErrorUtils.java
  src/test/java/com/michelin/ns4kafka/service/TopicServiceTest.java
Labels: bug

#623 Add the possibility to import specific connectors
  src/main/java/com/michelin/ns4kafka/controller/ConnectorController.java
  src/main/java/com/michelin/ns4kafka/service/ConnectorService.java
  src/test/java/com/michelin/ns4kafka/controller/ConnectorControllerTest.java
  src/test/java/com/michelin/ns4kafka/service/ConnectorServiceTest.java
Labels: feature
