Repository michelin/ns4kafka, pull requests merged in 2025-03, with the labels that each got.

#521 Add RapiDoc documentation
  README.md
Labels: documentation

#537 Set tab to space in Palantir format
  build.gradle
Labels: ci/cd

#541 Bump to Micronaut 4.7.6 and Gradle 8.11.1
  .github/workflows/release.yml
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: dependencies

#539 Add documentation about encryption
  README.md
  src/main/java/com/michelin/ns4kafka/service/ConnectClusterService.java
Labels: documentation

#544 Improve release workflow
  .github/workflows/release.yml
Labels: ci/cd

#538 Add new ContainsList validator
  src/main/java/com/michelin/ns4kafka/util/FormatErrorUtils.java
  src/main/java/com/michelin/ns4kafka/validation/ResourceValidator.java
  src/test/java/com/michelin/ns4kafka/model/ResourceValidatorTest.java
Labels: feature
