Repository michelin/ns4kafka, pull requests merged in 2025-05, with the labels that each got.

#559 Add error details on Gitlab group retrieval
  src/main/java/com/michelin/ns4kafka/security/auth/gitlab/GitlabAuthenticationProvider.java
Labels: bug

#560 Fix Bad Gitlab Token error display
  src/main/java/com/michelin/ns4kafka/security/auth/gitlab/GitlabAuthenticationProvider.java
Labels: bug

#561 Display Gitlab authentication error stacktrace
  src/main/java/com/michelin/ns4kafka/security/auth/gitlab/GitlabAuthenticationProvider.java
Labels: bug

#562 Run GitLab client on separate event loop and retry on timeout
  build.gradle
  src/main/java/com/michelin/ns4kafka/security/auth/gitlab/GitlabApiClient.java
  src/main/java/com/michelin/ns4kafka/security/auth/gitlab/GitlabAuthenticationProvider.java
  src/main/java/com/michelin/ns4kafka/service/executor/ConnectorAsyncExecutor.java
  src/main/java/com/michelin/ns4kafka/service/executor/KafkaAsyncExecutorScheduler.java
  src/main/resources/application.yml
Labels: bug

#563 Reduce log spam by default
  .docker/config/ns4kafka/logback.xml
  src/main/java/com/michelin/ns4kafka/service/ConnectClusterService.java
  src/main/resources/logback.xml
Labels: enhancement

#564 Add timeout retry on server side for Kafka Connect and Schema Registry
  README.md
  src/main/java/com/michelin/ns4kafka/security/auth/gitlab/GitlabAuthenticationProvider.java
  src/main/java/com/michelin/ns4kafka/service/client/connect/KafkaConnectClient.java
  src/main/java/com/michelin/ns4kafka/service/client/schema/SchemaRegistryClient.java
  src/main/java/com/michelin/ns4kafka/service/executor/AccessControlEntryAsyncExecutor.java
  src/main/resources/application.yml
  src/test/java/com/michelin/ns4kafka/security/auth/gitlab/GitlabAuthenticationProviderTest.java
Labels: enhancement

#565 Ignore case on authorization when comparing groups
  src/main/java/com/michelin/ns4kafka/repository/kafka/KafkaRoleBindingRepository.java
  src/main/java/com/michelin/ns4kafka/security/ResourceBasedSecurityRule.java
  src/main/java/com/michelin/ns4kafka/security/auth/AuthenticationService.java
  src/test/java/com/michelin/ns4kafka/integration/AclIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/integration/ApiResourcesIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/integration/ConnectClusterIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/integration/ExceptionHandlerIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/integration/NamespaceIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/integration/SchemaIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/integration/StreamIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/integration/TopicIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/integration/UserIntegrationTest.java
  src/test/java/com/michelin/ns4kafka/security/ResourceBasedSecurityRuleTest.java
  src/test/java/com/michelin/ns4kafka/security/auth/AuthenticationServiceTest.java
Labels: enhancement

#566 Expose server version
  build.gradle
  src/main/java/com/michelin/ns4kafka/controller/AkhqClaimProviderController.java
  src/main/java/com/michelin/ns4kafka/controller/ApiResourcesController.java
  src/main/java/com/michelin/ns4kafka/controller/AppInfoController.java
  src/main/java/com/michelin/ns4kafka/controller/ConnectorController.java
  src/main/java/com/michelin/ns4kafka/controller/ConsumerGroupController.java
  src/main/java/com/michelin/ns4kafka/controller/NamespaceController.java
  src/main/java/com/michelin/ns4kafka/controller/RoleBindingController.java
  src/main/java/com/michelin/ns4kafka/controller/SchemaController.java
  src/main/java/com/michelin/ns4kafka/controller/StreamController.java
  src/main/java/com/michelin/ns4kafka/controller/UserController.java
  src/main/java/com/michelin/ns4kafka/controller/acl/AclController.java
  src/main/java/com/michelin/ns4kafka/controller/acl/AclNonNamespacedController.java
  src/main/java/com/michelin/ns4kafka/controller/connect/ConnectClusterController.java
  src/main/java/com/michelin/ns4kafka/controller/connect/ConnectClusterNonNamespacedController.java
  src/main/java/com/michelin/ns4kafka/controller/generic/ResourceController.java
  src/main/java/com/michelin/ns4kafka/controller/quota/ResourceQuotaController.java
  src/main/java/com/michelin/ns4kafka/controller/quota/ResourceQuotaNonNamespacedController.java
  src/main/java/com/michelin/ns4kafka/controller/topic/TopicController.java
  src/main/java/com/michelin/ns4kafka/controller/topic/TopicNonNamespacedController.java
  src/main/java/com/michelin/ns4kafka/log/KafkaLogListener.java
  src/main/java/com/michelin/ns4kafka/model/AccessControlEntry.java
  src/main/java/com/michelin/ns4kafka/model/AppInfo.java
  src/main/java/com/michelin/ns4kafka/property/AkhqProperties.java
  src/main/java/com/michelin/ns4kafka/property/KafkaStoreProperties.java
  src/main/java/com/michelin/ns4kafka/property/Ns4KafkaProperties.java
  src/main/java/com/michelin/ns4kafka/property/SecurityProperties.java
  src/main/java/com/michelin/ns4kafka/repository/kafka/KafkaAccessControlEntryRepository.java
  src/main/java/com/michelin/ns4kafka/repository/kafka/KafkaStore.java
  src/main/java/com/michelin/ns4kafka/security/ResourceBasedSecurityRule.java
  src/main/java/com/michelin/ns4kafka/security/auth/AuthenticationService.java
  src/main/java/com/michelin/ns4kafka/security/auth/gitlab/GitlabAuthenticationProvider.java
  src/main/java/com/michelin/ns4kafka/security/auth/gitlab/GitlabAuthenticationService.java
  src/main/java/com/michelin/ns4kafka/security/auth/ldap/LdapAuthenticationMapper.java
  src/main/java/com/michelin/ns4kafka/security/auth/local/LocalUserAuthenticationProvider.java
  src/main/java/com/michelin/ns4kafka/service/AclService.java
  src/main/java/com/michelin/ns4kafka/service/ConnectClusterService.java
  src/main/java/com/michelin/ns4kafka/service/ConnectorService.java
  src/main/java/com/michelin/ns4kafka/service/ConsumerGroupService.java
  src/main/java/com/michelin/ns4kafka/service/NamespaceService.java
  src/main/java/com/michelin/ns4kafka/service/ResourceQuotaService.java
  src/main/java/com/michelin/ns4kafka/service/RoleBindingService.java
  src/main/java/com/michelin/ns4kafka/service/SchemaService.java
  src/main/java/com/michelin/ns4kafka/service/StreamService.java
  src/main/java/com/michelin/ns4kafka/service/TopicService.java
  src/main/java/com/michelin/ns4kafka/service/client/connect/KafkaConnectClient.java
  src/main/java/com/michelin/ns4kafka/service/executor/ConsumerGroupAsyncExecutor.java
  src/main/java/com/michelin/ns4kafka/service/executor/KafkaAsyncExecutorScheduler.java
  src/main/java/com/michelin/ns4kafka/service/executor/TopicAsyncExecutor.java
  src/main/java/com/michelin/ns4kafka/service/executor/UserAsyncExecutor.java
  src/main/resources/application.yml
  src/test/java/com/michelin/ns4kafka/controller/AkhqClaimProviderControllerTest.java
  src/test/java/com/michelin/ns4kafka/controller/AkhqClaimProviderControllerV3Test.java
  src/test/java/com/michelin/ns4kafka/controller/AppInfoControllerTest.java
  src/test/java/com/michelin/ns4kafka/security/ResourceBasedSecurityRuleTest.java
  src/test/java/com/michelin/ns4kafka/security/auth/AuthenticationServiceTest.java
  src/test/java/com/michelin/ns4kafka/security/auth/local/LocalUserAuthenticationProviderTest.java
  src/test/java/com/michelin/ns4kafka/service/ConnectClusterServiceTest.java
  src/test/java/com/michelin/ns4kafka/service/executor/TopicAsyncExecutorTest.java
Labels: feature

#568 Lower HTTP client timeouts
  README.md
  src/main/resources/application.yml
Labels: enhancement
